/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ProcesarDato extends javax.swing.JPanel {

    /**
     * Creates new form ProcesarDato
     */
    public ProcesarDato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDLabel = new javax.swing.JLabel();
        IDtf = new javax.swing.JTextField();
        procesarDatoB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTrama = new javax.swing.JTable();
        Promedio = new javax.swing.JLabel();
        promedioLabel = new javax.swing.JLabel();

        IDLabel.setText("ID:");

        procesarDatoB.setText("Procesar Dato");
        procesarDatoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarDatoBActionPerformed(evt);
            }
        });

        TablaTrama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID sensor", "Valor", "Fecha Y Hora", "Procesamiento"
            }
        ));
        jScrollPane1.setViewportView(TablaTrama);

        Promedio.setText("Promedio:");

        promedioLabel.setText("No Aplica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(procesarDatoB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(Promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(promedioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(procesarDatoB)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promedioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void procesarDatoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarDatoBActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)TablaTrama.getModel();
        model.setRowCount(0);
        ArrayList<Object[]> rows = Control.Gestion.procesarDato(Integer.parseInt(IDtf.getText()));
        
        if(rows.size() != 0){
            
            int promedio = 0;
        
            for (int i = 0; i < rows.size(); i++) {

                promedio += (int)rows.get(i)[3];
            }

            promedio = promedio / rows.size();
            promedioLabel.setText(String.valueOf(promedio));
            
        }
        else{
            promedioLabel.setText("N/A");
        }
        
        
        
        for (int i = 0; i < rows.size(); i++) {
            model.addRow(rows.get(i));
        }
    }//GEN-LAST:event_procesarDatoBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDtf;
    private javax.swing.JLabel Promedio;
    private javax.swing.JTable TablaTrama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton procesarDatoB;
    private javax.swing.JLabel promedioLabel;
    // End of variables declaration//GEN-END:variables
}
