/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author user
 */
public class VistaInicial extends javax.swing.JFrame {

    private EnviarDato enviar_dato = new EnviarDato();
    private MostrarDatos mostrar_datos = new MostrarDatos();
    private ProcesarDato procesar_dato = new ProcesarDato();
    
    public VistaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enviarDatoB = new javax.swing.JButton();
        mostrarDatoB = new javax.swing.JButton();
        procesarDatoB = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enviarDatoB.setText("Enviar Dato");
        enviarDatoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarDatoBActionPerformed(evt);
            }
        });

        mostrarDatoB.setText("Mostrar Datos");
        mostrarDatoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarDatoBActionPerformed(evt);
            }
        });

        procesarDatoB.setText("Procesar Dato");
        procesarDatoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarDatoBActionPerformed(evt);
            }
        });

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enviarDatoB)
                        .addGap(27, 27, 27)
                        .addComponent(mostrarDatoB)
                        .addGap(31, 31, 31)
                        .addComponent(procesarDatoB)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarDatoB)
                    .addComponent(mostrarDatoB)
                    .addComponent(procesarDatoB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarDatoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarDatoBActionPerformed
          panelPrincipal.setVisible(false);
          panelPrincipal.removeAll();
          panelPrincipal.add(enviar_dato);
          panelPrincipal.setVisible(true);
    }//GEN-LAST:event_enviarDatoBActionPerformed

    private void mostrarDatoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarDatoBActionPerformed
          panelPrincipal.setVisible(false);
          panelPrincipal.removeAll();
          panelPrincipal.add(mostrar_datos);
          panelPrincipal.setVisible(true);
    }//GEN-LAST:event_mostrarDatoBActionPerformed

    private void procesarDatoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarDatoBActionPerformed
          panelPrincipal.setVisible(false);
          panelPrincipal.removeAll();
          panelPrincipal.add(procesar_dato);
          panelPrincipal.setVisible(true);
    }//GEN-LAST:event_procesarDatoBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarDatoB;
    private javax.swing.JButton mostrarDatoB;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton procesarDatoB;
    // End of variables declaration//GEN-END:variables
}
